"""
Report Generator
-----------------
Generates a professional downloadable PDF report of the full analysis.
Uses fpdf2 for PDF creation.
"""
from fpdf import FPDF
from typing import List, Dict, Any, Optional
from datetime import datetime
import io

def safe_text(text: Any) -> str:
    if not text: return ""
    s = str(text)
    replacements = {
        '\u2013': '-', '\u2014': '-', '\u2018': "'", '\u2019': "'",
        '\u201c': '"', '\u201d': '"', '\u2026': '...', '\u00a0': ' ',
        '\u2022': '-', '\u00ad': '-', '\u200b': ''
    }
    for k, v in replacements.items():
        s = s.replace(k, v)
    return s.encode('latin-1', 'replace').decode('latin-1')

class ReportPDF(FPDF):
    """Custom FPDF subclass with header/footer"""

    def __init__(self, domain: str, report_date: str):
        super().__init__()
        self.domain = domain
        self.report_date = report_date

    def header(self):
        self.set_fill_color(15, 23, 42)       # slate-900
        self.rect(0, 0, 210, 18, 'F')
        self.set_font('Helvetica', 'B', 11)
        self.set_text_color(255, 255, 255)
        self.set_xy(10, 4)
        self.cell(0, 10, f'SaaS Market Gap Analyzer  |  {self.domain}', ln=False)
        self.set_xy(0, 4)
        self.cell(200, 10, self.report_date, align='R', ln=False)
        self.set_text_color(0, 0, 0)
        self.ln(16)

    def footer(self):
        self.set_y(-12)
        self.set_font('Helvetica', 'I', 8)
        self.set_text_color(130, 130, 130)
        self.cell(0, 10, f'Page {self.page_no()} | Confidential - Generated by SaaS Gap Analyzer', align='C')

    def section_title(self, title: str):
        self.set_fill_color(241, 245, 249)     # slate-100
        self.set_font('Helvetica', 'B', 13)
        self.set_text_color(15, 23, 42)
        self.set_x(10)
        self.cell(190, 9, safe_text(title), fill=True, ln=True)
        self.ln(3)

    def kv_row(self, label: str, value: str):
        self.set_font('Helvetica', 'B', 9)
        self.set_text_color(100, 116, 139)
        self.set_x(12)
        self.cell(55, 7, safe_text(label.upper()), ln=False)
        self.set_font('Helvetica', '', 9)
        self.set_text_color(15, 23, 42)
        self.multi_cell(130, 7, safe_text(str(value)), ln=True)

    def score_badge(self, score: float) -> tuple:
        if score >= 75:
            return (22, 163, 74)    # green-600
        elif score >= 55:
            return (234, 179, 8)    # yellow-500
        else:
            return (239, 68, 68)    # red-500


def generate_analysis_report(
    domain_config: Dict[str, Any],
    pain_points: List[Dict],
    gaps: List[Dict],
    opportunities: List[Dict],
    summary: Dict[str, Any]
) -> bytes:
    """
    Generate a complete PDF report.

    Returns:
        bytes: Raw PDF bytes ready to stream as file download.
    """
    report_date = datetime.utcnow().strftime("%B %d, %Y")
    domain = domain_config.get("domain", "Unknown Domain")

    pdf = ReportPDF(domain=domain, report_date=report_date)
    pdf.set_auto_page_break(auto=True, margin=20)
    pdf.set_margins(10, 20, 10)

    # -----------------------------------------------
    # COVER PAGE
    # -----------------------------------------------
    pdf.add_page()
    pdf.set_fill_color(15, 23, 42)
    pdf.rect(0, 0, 210, 297, 'F')

    pdf.set_font('Helvetica', 'B', 28)
    pdf.set_text_color(255, 255, 255)
    pdf.set_xy(20, 70)
    pdf.multi_cell(170, 14, safe_text('SaaS Market Gap\nAnalysis Report'), align='C')

    pdf.set_font('Helvetica', '', 14)
    pdf.set_text_color(148, 163, 184)
    pdf.set_xy(20, 120)
    pdf.cell(170, 10, safe_text(domain), align='C', ln=True)

    pdf.set_font('Helvetica', '', 11)
    pdf.set_xy(20, 140)
    pdf.cell(170, 10, f'Generated on {report_date}', align='C', ln=True)

    # KPI strip on cover
    pdf.set_fill_color(30, 41, 59)
    pdf.rect(10, 190, 190, 50, 'F')
    kpis = [
        ("Pain Points", str(len(pain_points))),
        ("Gaps Found", str(len(gaps))),
        ("Opportunities", str(len(opportunities))),
        ("Avg Score", f"{summary.get('average_opportunity_score', 0):.1f}"),
    ]
    col_w = 47
    for i, (label, val) in enumerate(kpis):
        x = 10 + i * col_w + 5
        pdf.set_xy(x, 198)
        pdf.set_font('Helvetica', 'B', 20)
        pdf.set_text_color(99, 179, 237)
        pdf.cell(col_w - 5, 12, val, align='C', ln=True)
        pdf.set_xy(x, 213)
        pdf.set_font('Helvetica', '', 8)
        pdf.set_text_color(148, 163, 184)
        pdf.cell(col_w - 5, 8, label.upper(), align='C')

    # -----------------------------------------------
    # PAGE 2: EXECUTIVE SUMMARY
    # -----------------------------------------------
    pdf.add_page()
    pdf.set_text_color(0, 0, 0)

    pdf.section_title("01  Executive Summary")

    pdf.set_font('Helvetica', '', 9)
    pdf.set_text_color(51, 65, 85)
    summary_text = (
        f"This report presents the findings of an AI-driven market gap analysis for the "
        f"{domain} domain, targeting {domain_config.get('target_market', 'N/A')}. "
        f"The analysis identified {len(pain_points)} customer pain points, synthesized "
        f"{len(gaps)} market gaps, and ranked {len(opportunities)} actionable opportunities "
        f"by market potential, execution ease, defensibility, and timing. "
        f"The top-ranked opportunity carries an overall score of "
        f"{opportunities[0]['overall_score']:.1f}/100 with a TAM of {opportunities[0]['tam_estimate']}."
        if opportunities else
        f"This report presents findings for the {domain} domain. No opportunities were scored."
    )
    pdf.set_x(10)
    pdf.multi_cell(190, 6, safe_text(summary_text))
    pdf.ln(5)

    pdf.section_title("Domain Configuration")
    pdf.kv_row("Domain", domain_config.get("domain", "—"))
    pdf.kv_row("Product Category", domain_config.get("product_category", "—"))
    pdf.kv_row("Target Market", domain_config.get("target_market", "—"))
    pdf.kv_row("Industry TAM", f"${domain_config.get('industry_tam_billions', 50):.0f}B")
    pdf.kv_row("Market Growth Rate", f"{domain_config.get('market_growth_rate', 12):.1f}% / year")
    pdf.ln(4)

    # -----------------------------------------------
    # PAGE 3: PAIN POINTS TABLE
    # -----------------------------------------------
    pdf.add_page()
    pdf.section_title("02  Customer Pain Points")

    # Table header
    headers = ["#", "Theme", "Severity", "Frequency", "Personas"]
    col_widths = [8, 78, 22, 22, 60]
    pdf.set_fill_color(15, 23, 42)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 8)
    pdf.set_x(10)
    for h, w in zip(headers, col_widths):
        pdf.cell(w, 8, h, border=0, fill=True, align='C')
    pdf.ln()

    # Table rows
    for i, pp in enumerate(sorted(pain_points, key=lambda x: x.get('severity_score', 0), reverse=True)):
        pdf.set_fill_color(248, 250, 252) if i % 2 == 0 else pdf.set_fill_color(255, 255, 255)
        pdf.set_text_color(15, 23, 42)
        pdf.set_font('Helvetica', '', 8)
        row_y = pdf.get_y()
        pdf.set_x(10)
        pdf.cell(col_widths[0], 8, str(i + 1), fill=True, align='C')
        
        safe_theme = safe_text(pp.get('theme', '')[:55])
        pdf.cell(col_widths[1], 8, safe_theme, fill=True)

        sev = pp.get('severity_score', 0)
        r, g, b = (22, 163, 74) if sev >= 7 else (234, 179, 8) if sev >= 5 else (239, 68, 68)
        pdf.set_text_color(r, g, b)
        pdf.set_font('Helvetica', 'B', 8)
        pdf.cell(col_widths[2], 8, f"{sev:.1f}/10", fill=True, align='C')

        pdf.set_text_color(15, 23, 42)
        pdf.set_font('Helvetica', '', 8)
        pdf.cell(col_widths[3], 8, str(pp.get('frequency', 0)), fill=True, align='C')
        personas_list = pp.get('affected_personas', [])
        if not isinstance(personas_list, list):
            personas_list = [str(personas_list)]
        personas = safe_text(", ".join(personas_list)[:38])
        pdf.cell(col_widths[4], 8, personas, fill=True)
        pdf.ln()

    pdf.ln(4)

    # -----------------------------------------------
    # PAGE 4: GAPS TABLE
    # -----------------------------------------------
    pdf.add_page()
    pdf.section_title("03  Market Gaps Identified")

    gap_headers = ["#", "Gap Name", "Type", "Coverage", "Severity"]
    gap_widths = [8, 90, 35, 27, 30]
    pdf.set_fill_color(15, 23, 42)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 8)
    pdf.set_x(10)
    for h, w in zip(gap_headers, gap_widths):
        pdf.cell(w, 8, h, border=0, fill=True, align='C')
    pdf.ln()

    for i, gap in enumerate(gaps):
        pdf.set_fill_color(248, 250, 252) if i % 2 == 0 else pdf.set_fill_color(255, 255, 255)
        pdf.set_text_color(15, 23, 42)
        pdf.set_font('Helvetica', '', 8)
        pdf.set_x(10)
        pdf.cell(gap_widths[0], 8, str(i + 1), fill=True, align='C')
        safe_name = safe_text(gap.get('name', '')[:52])
        pdf.cell(gap_widths[1], 8, safe_name, fill=True)

        # Color-coded gap type
        gap_type = gap.get('gap_type', 'Partial gap')
        type_color = {
            'Complete gap': (239, 68, 68),
            'Partial gap':  (234, 179, 8),
            'Competitive gap': (99, 102, 241)
        }.get(gap_type, (100, 116, 139))
        pdf.set_text_color(*type_color)
        pdf.set_font('Helvetica', 'B', 7)
        pdf.cell(gap_widths[2], 8, gap_type, fill=True, align='C')

        pdf.set_text_color(15, 23, 42)
        pdf.set_font('Helvetica', '', 8)
        cov = gap.get('coverage_percentage', 0)
        pdf.cell(gap_widths[3], 8, f"{cov:.0f}%", fill=True, align='C')
        pdf.cell(gap_widths[4], 8, f"{gap.get('severity_score', 0):.1f}/10", fill=True, align='C')
        pdf.ln()

    pdf.ln(4)

    # -----------------------------------------------
    # PAGES 5+: RANKED OPPORTUNITIES (1 per page for top 5)
    # -----------------------------------------------
    for rank, opp in enumerate(opportunities[:5], start=1):
        pdf.add_page()
        safe_opp_name = safe_text(opp.get('name', ''))
        pdf.section_title(f"04.{rank}  Opportunity #{rank}: {safe_opp_name}")

        # Score header block
        score = opp.get('overall_score', 0)
        r, g, b = pdf.score_badge(score)
        pdf.set_fill_color(r, g, b)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font('Helvetica', 'B', 22)
        pdf.set_x(10)
        pdf.cell(40, 16, f"{score:.1f}", fill=True, align='C')
        pdf.set_font('Helvetica', '', 9)
        pdf.set_fill_color(241, 245, 249)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(148, 16, "  Overall Opportunity Score / 100", fill=True)
        pdf.ln(18)

        # Score breakdown grid
        scores = [
            ("Market Potential", opp.get('market_potential_score', 0), (59, 130, 246)),
            ("Execution Ease",   opp.get('execution_ease_score', 0),   (34, 197, 94)),
            ("Defensibility",    opp.get('defensibility_score', 0),    (168, 85, 247)),
            ("Timing",           opp.get('timing_score', 0),           (249, 115, 22)),
        ]
        for label, val, color in scores:
            pdf.set_x(12)
            pdf.set_font('Helvetica', '', 8)
            pdf.set_text_color(100, 116, 139)
            pdf.cell(60, 6, label.upper())

            # Bar background
            bar_x = 70
            bar_y = pdf.get_y() + 1
            bar_max_w = 110
            pdf.set_fill_color(226, 232, 240)
            pdf.rect(bar_x, bar_y, bar_max_w, 4, 'F')
            # Bar fill
            pdf.set_fill_color(*color)
            pdf.rect(bar_x, bar_y, max(2, bar_max_w * val / 100), 4, 'F')
            # Label
            pdf.set_xy(bar_x + bar_max_w + 3, pdf.get_y())
            pdf.set_font('Helvetica', 'B', 9)
            pdf.set_text_color(*color)
            pdf.cell(20, 6, f"{val:.0f}")
            pdf.ln(7)

        pdf.ln(3)

        # Market details
        pdf.section_title("Market Details")
        pdf.kv_row("TAM Estimate", opp.get('tam_estimate', '—'))
        pdf.kv_row("Year 3 ARR Potential", opp.get('year3_arr_estimate', '—'))
        pdf.kv_row("Competitive Threat", opp.get('threat_level', '—'))
        pdf.kv_row("Direct Competitors", str(opp.get('direct_competitors_count', 0)))
        
        target_p = opp.get('target_personas', [])
        if not isinstance(target_p, list): target_p = [str(target_p)]
        pdf.kv_row("Target Personas", ", ".join(target_p))

        pdf.ln(3)
        pdf.section_title("Implementation Estimate")
        pdf.kv_row("Estimated Timeline", f"{opp.get('estimated_effort_months', '?')} months")
        pdf.kv_row("Estimated Team Size", f"{opp.get('estimated_team_size', '?')} engineers")
        cost = opp.get('estimated_cost_usd', 0)
        pdf.kv_row("Estimated Cost", f"${cost / 1000:.0f}K USD" if cost else "—")

        pdf.ln(3)
        pdf.section_title("Risk Assessment")
        pdf.set_x(12)
        pdf.set_font('Helvetica', '', 9)
        pdf.set_text_color(51, 65, 85)
        safe_risk = safe_text(opp.get('risk_summary', '—'))
        pdf.multi_cell(186, 6, safe_risk)

    # -----------------------------------------------
    # FINAL PAGE: Methodology
    # -----------------------------------------------
    pdf.add_page()
    pdf.section_title("05  Methodology")
    pdf.set_font('Helvetica', '', 9)
    pdf.set_text_color(51, 65, 85)
    methodology = (
        "This analysis was conducted using a four-stage AI-assisted pipeline:\n\n"
        "1. PAIN POINT SYNTHESIS - Groq (Llama 3) was prompted with the user's domain context "
        "to generate a realistic set of customer survey pain points grounded in publicly observable "
        "patterns from platforms like G2, Capterra, and Gartner reports.\n\n"
        "2. COMPETITOR FEATURE MAPPING - A curated set of competitor products and their publicly "
        "known feature sets was referenced to establish the current solution landscape.\n\n"
        "3. GAP IDENTIFICATION - Each pain point was cross-referenced against competitor features "
        "using Groq semantic analysis to identify Complete, Partial, and Competitive gaps.\n\n"
        "4. OPPORTUNITY SCORING - Gaps were scored on four dimensions: Market Potential (40%), "
        "Execution Ease (30%), Defensibility (20%), and Timing (10%). TAM and ARR estimates "
        "use industry-standard penetration rate assumptions (5% Year-3 market share).\n\n"
        "Scores are indicative and should be validated with primary market research."
    )
    pdf.set_x(10)
    pdf.multi_cell(190, 6, safe_text(methodology))

    # Return as bytes
    return bytes(pdf.output())
